<?php
/**
 * PHP <-> JS grade policy parity report.
 *
 * Loads the real assets/js/grade-estimator.js — not a copy — and replays the
 * vectors generated by Grade_calculator through its exported policy functions.
 * A green run is the evidence that the front-end estimator agrees with the
 * grade engine; nothing else in the codebase asserts that.
 *
 * Standalone page: it must not depend on header.php's asset stack, so a change
 * there can never mask a parity failure.
 */
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Grade policy parity — PHP vs JS</title>
    <style>
        body { font-family: ui-monospace, Menlo, Consolas, monospace; margin: 2rem; color: #222; }
        h1 { font-size: 1.25rem; }
        #summary { padding: 1rem; border-radius: 4px; font-size: 1.05rem; margin: 1rem 0; }
        .pass { background: #d4edda; border: 1px solid #28a745; }
        .fail { background: #f8d7da; border: 1px solid #dc3545; }
        .busy { background: #e2e3e5; border: 1px solid #6c757d; }
        table { border-collapse: collapse; width: 100%; font-size: .8125rem; }
        th, td { border: 1px solid #ccc; padding: .35rem .5rem; text-align: left; vertical-align: top; }
        th { background: #f1f1f1; }
        td.args { max-width: 34rem; word-break: break-all; }
        .meta { color: #666; font-size: .8125rem; }
    </style>
</head>
<body>
    <h1>Grade policy parity — Grade_calculator (PHP) vs grade-estimator.js</h1>
    <p class="meta">
        Vectors are generated by the PHP model itself, so its answers are the
        expectation by definition. Every row below is a JS result compared
        against one. Run this after any grading change on either side.
    </p>

    <div id="summary" class="busy">Loading vectors…</div>
    <div id="failures"></div>

    <script src="<?= base_url('assets/js/grade-estimator.js') ?>"></script>
    <script>
    (function () {
        'use strict';

        var TOLERANCE = 1e-9;

        function summary(cls, html) {
            var node = document.getElementById('summary');
            node.className = cls;
            node.innerHTML = html;
        }

        /**
         * null is compared strictly: a JS 0 where the PHP returned null is a
         * real failure (that exact bug — 'INC' silently becoming 5.00 — is why
         * transmute() returns null instead of a formatted string).
         */
        function same(actual, expected) {
            if (expected === null || actual === null) {
                return expected === null && actual === null;
            }
            if (typeof expected === 'number' || typeof actual === 'number') {
                var a = parseFloat(actual), e = parseFloat(expected);
                if (isNaN(a) || isNaN(e)) { return false; }
                return Math.abs(a - e) < TOLERANCE;
            }
            if (Array.isArray(expected)) {
                if (!Array.isArray(actual) || actual.length !== expected.length) { return false; }
                return expected.every(function (v, i) { return same(actual[i], v); });
            }
            if (typeof expected === 'object') {
                return Object.keys(expected).every(function (k) { return same(actual[k], expected[k]); });
            }
            return String(actual) === String(expected);
        }

        function run(fn, args, policy) {
            switch (fn) {
                case 'transmute':
                    return window.GradePolicy.transmute(args[0], args[1], policy);
                case 'component':
                    return window.GradePolicy.component(args[0], args[1], args[2], args[3], policy);
                case 'term_grade':
                    return window.GradePolicy.termGrade(args[0], args[1], args[2], policy);
                case 'final_grade':
                    return window.GradePolicy.finalGrade(args[0], args[1], args[2], policy);
                case 'estimate_initial':
                    // End-to-end: build the opening slider state from the
                    // payload and flatten to the shape the PHP reported.
                    var data = args[0];
                    var result = window.GradePolicy.estimateAll(
                        data, window.GradePolicy.initialState(data)
                    );
                    return {
                        midterm: result.midterm.grade,
                        final: result.final.grade,
                        overall: result.overall
                    };
                default:
                    throw new Error('unmapped policy function: ' + fn);
            }
        }

        var request = new XMLHttpRequest();
        request.open('GET', '<?= base_url('grade_audit/policyvectors') ?>', true);
        request.onload = function () {
            var data;
            try {
                data = JSON.parse(request.responseText);
            } catch (e) {
                summary('fail', 'Could not parse policyvectors output — is the session still admin?');
                return;
            }

            var failures = [];
            var passed = 0;

            data.vectors.forEach(function (v, index) {
                var actual, error = null;
                try {
                    actual = run(v.fn, v.args, data.policy);
                } catch (e) {
                    error = e.message;
                }
                if (error === null && same(actual, v.expected)) {
                    passed++;
                } else {
                    failures.push({
                        index: index, fn: v.fn, args: v.args,
                        expected: v.expected,
                        actual: error === null ? actual : ('threw: ' + error)
                    });
                }
            });

            if (failures.length === 0) {
                summary('pass',
                    '<strong>PARITY OK</strong> — ' + passed + ' / ' + data.vector_count +
                    ' vectors match.<br><span class="meta">vectors generated ' + data.generated_at + '</span>');
                return;
            }

            summary('fail',
                '<strong>PARITY FAILED</strong> — ' + failures.length + ' of ' + data.vector_count +
                ' vectors differ. The estimator is reporting grades the engine would not.');

            var rows = failures.map(function (f) {
                return '<tr><td>' + f.index + '</td><td>' + f.fn +
                       '</td><td class="args">' + JSON.stringify(f.args) +
                       '</td><td>' + JSON.stringify(f.expected) +
                       '</td><td>' + JSON.stringify(f.actual) + '</td></tr>';
            }).join('');

            document.getElementById('failures').innerHTML =
                '<table><thead><tr><th>#</th><th>fn</th><th>args</th>' +
                '<th>PHP (expected)</th><th>JS (actual)</th></tr></thead><tbody>' +
                rows + '</tbody></table>';
        };
        request.onerror = function () {
            summary('fail', 'Could not reach /grade_audit/policyvectors.');
        };
        request.send();
    })();
    </script>
</body>
</html>
